name = "PaCMAP"
uuid = "742de0ed-86c0-4271-901a-ffbeba893890"
authors = ["Gilles-Philippe Morin <gphmorin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
